
service: events 

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-east-1

functions:
  getNewEventId:
    handler: handler.getNewEventId
    events:
      - http:
          path: events/getNewEventId
          method: get
          cors: true
  addEvent:
    handler: handler.addEvent
    events:
      - http:
          path: events
          method: post
          cors: true
  updateEvent:
    handler: handler.updateEvent
    events:
      - http:
          path: events
          method: put
          cors: true
  deleteEvent:
    handler: handler.deleteEvent
    events:
      - http:
          path: events/{id}
          method: delete
          request:
            parameters:
              paths:
                id: true
          cors: true
  assignStreamToEvent:
    handler: handler.assignStreamToEvent
    events:
      - http:
          path: events/{id}/streams
          method: post
          request:
            parameters:
              paths:
                id: true
          cors: true
  unassignStreamFromEvent:
    handler: handler.unassignStreamFromEvent
    events:
      - http:
          path: events/{id}/streams
          method: delete
          request:
            parameters:
              paths:
                id: true
          cors: true
  assignMusicianToEvent:
    handler: handler.assignMusicianToEvent
    events:
      - http:
          path: events/{id}/musicians
          method: post
          request:
            parameters:
              paths:
                id: true
          cors: true
  unassignMusicianFromEvent:
    handler: handler.unassignMusicianFromEvent
    events:
      - http:
          path: events/{id}/musicians
          method: delete
          request:
            parameters:
              paths:
                id: true
          cors: true

