
service: musicians 

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-east-1

functions:
  loginMusician:
    handler: handler.login
    events:
      - http:
          path: musician/login
          method: post
          cors: true
  addMusician:
    handler: handler.addMusician
    events:
      - http:
          path: musicians
          method: post
          cors: true
  updateMusician:
    handler: handler.updateMusician
    events:
      - http:
          path: musicians
          method: put
          cors: true
  deleteMusician:
    handler: handler.deleteMusician
    events:
      - http:
          path: musician/{id}
          method: delete
          integration: lambda
          request:
            parameters:
              paths:
                id: true
          cors: true

