
service: musicians 

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-east-1

functions:
  getNewMusicianId:
    handler: handler.getNewMusicianId
    events:
      - http:
          path: musicians/getNewMusicianId
          method: get
          cors: true
  addMusician:
    handler: handler.addMusician
    events:
      - http:
          path: musicians
          method: post
          cors: true
  updateMusician:
    handler: handler.updateMusician
    events:
      - http:
          path: musicians
          method: put
          cors: true
  deleteMusician:
    handler: handler.deleteMusician
    events:
      - http:
          path: musicians/{id}
          method: delete
          request:
            parameters:
              paths:
                id: true
          cors: true

