
service: users 

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-east-1

functions:
  login:
    handler: handler.login
    events:
      - http:
          path: users/login
          method: post
          cors: true
  createUser:
    handler: handler.createUser
    events:
      - http:
          path: users
          method: post
          cors: true
  updateUser:
    handler: handler.updateUser
    events:
      - http:
          path: users/{id}
          method: put
          integration: lambda
          request:
            parameters:
              paths:
                id: true
          cors: true
  deleteUser:
    handler: handler.deleteUser
    events:
      - http:
          path: users/{id}
          method: delete
          integration: lambda
          request:
            parameters:
              paths:
                id: true
          cors: true

