
service: users 

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-east-1

functions:
  getNewUserId:
    handler: handler.getNewUserId
    events:
      - http:
          path: users/getNewUserId
          method: get
          cors: true
  login:
    handler: handler.login
    events:
      - http:
          path: users/login
          method: post
          cors: true
  addUser:
    handler: handler.addUser
    events:
      - http:
          path: users
          method: post
          cors: true
  updateUser:
    handler: handler.updateUser
    events:
      - http:
          path: users
          method: put
          cors: true
  deleteUser:
    handler: handler.deleteUser
    events:
      - http:
          path: users/{id}
          method: delete
          request:
            parameters:
              paths:
                id: true
          cors: true

