
service: streams 

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-east-1

functions:
  getNewStreamId:
    handler: handler.getNewStreamId
    events:
      - http:
          path: streams/getNewStreamId
          method: get
          cors: true
  addStream:
    handler: handler.addStream
    events:
      - http:
          path: streams
          method: post
          cors: true
  updateStream:
    handler: handler.updateStream
    events:
      - http:
          path: streams
          method: put
          cors: true
  deleteStream:
    handler: handler.deleteStream
    events:
      - http:
          path: streams/{id}
          method: delete
          request:
            parameters:
              paths:
                id: true
          cors: true

